<?php

/**
 * Delete landing page and menu endpoints rest config.
 */
function ah_services_update_8100() {
  if (\Drupal::configFactory()->getEditable('rest.resource.landing_page_api')) {
    \Drupal::configFactory()->getEditable('rest.resource.landing_page_api')->delete();
  }
  if (\Drupal::configFactory()->getEditable('rest.resource.menu_api')) {
    \Drupal::configFactory()->getEditable('rest.resource.menu_api')->delete();
  }
}
