field.widget.settings.reference_value_select:
  type: mapping
  label: 'Reference value pair select widget settings.'
  mapping:
    size_value:
      type: integer
      label: 'Size of the value textfield'
    placeholder_value:
      type: string
      label: 'Value placeholder'

field.widget.settings.reference_value_autocomplete_widget:
  type: mapping
  label: 'Reference value pair autocomplete widget settings.'
  mapping:
    size_value:
      type: integer
      label: 'Size of the value textfield'
    placeholder_value:
      type: string
      label: 'Value placeholder'
    size_er:
      type: integer
      label: 'Size of the entity reference textfield'
    placeholder_er:
      type: string
      label: 'Entity reference placeholder'
    match_operator:
      type: string
      label: 'Autocomplete matching'

field.formatter.settings.reference_value_formatter:
  type: mapping
  label: 'Reference value formatter settings'
  mapping:
    display_invalid_reference:
      type: integer
      label: 'Display invalid reference'
    invalid_reference_label:
      type: string
      label: 'Invalid reference label'
